spring:
  application:
    name: cad_pgm-api
  profiles:
    active: dev # Se você não avisar nada, ele sobe como 'dev'
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

