spring:
  application:
    name: cad_pgm_api
  profiles:
    active: dev # Se você não avisar nada, ele sobe como 'dev'
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  servlet:
    multipart:
      max-file-size: 1536KB    # Exatos 1.5 MB (1.5 * 1024)
      max-request-size: 20480KB # Tamanho total da requisição 20MB
server:
  tomcat:
    max-swallow-size: -1  # O valor -1 diz ao Tomcat para nunca fechar a conexão de forma abrupta

